name = "contact-form"
main = "worker.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "taeyoon.kr/admin", zone_name = "taeyoon.kr" },
  { pattern = "taeyoon.kr/ip", zone_name = "taeyoon.kr" },
  { pattern = "taeyoon.kr/visitor/*", zone_name = "taeyoon.kr" },
  { pattern = "taeyoon.kr/api/*", zone_name = "taeyoon.kr" },
  { pattern = "taeyoon.kr/collect", zone_name = "taeyoon.kr" }
]

[[kv_namespaces]]
binding = "VISITOR_LOG"
id = "121c27d4ffbd44e393abbbf2fb9eb586"

[[kv_namespaces]]
binding = "VISITOR_ANALYTICS_KV"
id = "9cd1faa2076f43749f314d08e009b111"

[[kv_namespaces]]
binding = "SECURITY_DATA"
id = "9b7318d35c28442198fb6bc6b96c8879"

# Text module imports for HTML dashboards
[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true

[vars]
ALLOWED_ORIGIN = "https://taeyoon.kr"
ALLOWED_ORIGINS = "https://taeyoon.kr"
RESEND_API_KEY = "re_ELdJZkxn_ABDbdUDtmVNyMFUhj8oroUzi"